### ISSUE TITLE
test page

### ISSUE THREAD

**Issue by luwes** [WebReflection/nonchalance#4]
gh pages might need a new deploy
https://webreflection.github.io/nonchalance/test/ is not working on my end.

---

Very cool package! 

One thing that came to mind, is native built-in extends have the required `is` attribute which gives inspecting these elements some hint that it is augmented. Does nonchalance have something like this?

**Comment by WebReflection** [comment]
you can use any attribute you like ... usually `data-*` attributes are those suggested for custom stuff.

**Comment by luwes** [comment]
thanks for the quick fix
